version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend/mypla
    ports:
      - "3000:80"
    container_name: frontend
    restart: unless-stopped

volumes:
  postgres_data: