version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    #esto a diferencia de always, no inicia el contenedor si lo detenemos
    #en produccion si debe ir el "always" para que se inicie cuando se inicia el sistema
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      retries: 5
      
  frontend:
    build: ./frontend/mypla
    ports:
      - "3000:80"
    container_name: frontend
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - .env
    container_name: backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
