"""create topic recurrent

Revision ID: 0aae468f8f07
Revises: 7e290b3b75ce
Create Date: 2025-04-21 21:38:18.671079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aae468f8f07'
down_revision: Union[str, None] = '7e290b3b75ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicrecurrent',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('name_day', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_name'], ['topic.topic_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_name', 'user_id', 'start', 'name_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topicrecurrent')
    # ### end Alembic commands ###
