"""crearte profesionalTopic

Revision ID: 26b5a5049b6c
Revises: b43ed2b4c429
Create Date: 2025-04-21 19:51:17.345402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b5a5049b6c'
down_revision: Union[str, None] = 'b43ed2b4c429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesionaltopic',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_name'], ['topic.topic_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profesional.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_name', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesionaltopic')
    # ### end Alembic commands ###
