"""Create Table ProfessionalTopic

Revision ID: 2aba5c71ecf4
Revises: 67a6a5bdb255
Create Date: 2025-04-30 20:28:25.957538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aba5c71ecf4'
down_revision: Union[str, None] = '67a6a5bdb255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionaltopic',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('price_class', sa.Float(), nullable=False),
    sa.CheckConstraint('price_class > 0 ', name='check_price_valid'),
    sa.ForeignKeyConstraint(['prof_id'], ['professional.prof_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_name'], ['topic.topic_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_name', 'prof_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professionaltopic')
    # ### end Alembic commands ###
