"""Add check constraint

Revision ID: 51567d81c70a
Revises: e81aaaa00261
Create Date: 2025-04-24 22:49:38.491980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51567d81c70a'
down_revision: Union[str, None] = 'e81aaaa00261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
