"""disable topic recurrent and fix default in profesional

Revision ID: 5c619fcb6b93
Revises: 23fd5db11c79
Create Date: 2025-04-22 17:11:20.571661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c619fcb6b93'
down_revision: Union[str, None] = '23fd5db11c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topicrecurrent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicrecurrent',
    sa.Column('topic_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('name_day', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_name'], ['topic.topic_name'], name='topicrecurrent_topic_name_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'start', 'name_day'], ['recurrentschedule.user_id', 'recurrentschedule.start', 'recurrentschedule.name_day'], name='topicrecurrent_user_id_start_name_day_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_name', 'user_id', 'start', 'name_day', name='topicrecurrent_pkey')
    )
    # ### end Alembic commands ###
