"""Create Table Topic

Revision ID: 67a6a5bdb255
Revises: 8eb396d12730
Create Date: 2025-04-30 20:28:11.383886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a6a5bdb255'
down_revision: Union[str, None] = '8eb396d12730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
