"""to create add

Revision ID: 6c1035060466
Revises: c885033a4f7c
Create Date: 2025-05-23 19:58:31.710287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1035060466'
down_revision: Union[str, None] = 'c885033a4f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('create', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('specificschedule',sa.Column('create', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'),nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'create')
    # ### end Alembic commands ###
