"""Add category

Revision ID: 701cd1040c24
Revises: f6b8bd90788d
Create Date: 2025-06-17 16:49:31.385429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701cd1040c24'
down_revision: Union[str, None] = 'f6b8bd90788d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_name')
    )
    op.add_column('topic', sa.Column('category_name', sa.String(), nullable=False))
    op.create_foreign_key('fk_topic_category', 'topic', 'category', ['category_name'], ['category_name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_topic_category', 'topic', type_='foreignkey')
    op.drop_column('topic', 'category_name')
    op.drop_table('category')
    # ### end Alembic commands ###
