"""create Table Recurrent

Revision ID: 74006464cd14
Revises: 232d256614cd
Create Date: 2025-04-21 16:08:29.915870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74006464cd14'
down_revision: Union[str, None] = '232d256614cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrentschedule',
    sa.Column('name_day', sa.String(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.CheckConstraint("name_day IN ('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo')", name='check_name_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['profesional.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name_day', 'start', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrentschedule')
    # ### end Alembic commands ###
