"""update check week

Revision ID: 7604af5afa08
Revises: 6d9bc9d71e54
Create Date: 2025-06-03 16:37:49.511332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7604af5afa08'
down_revision: Union[str, None] = '6d9bc9d71e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_week_valid', 'recurrentschedule', type_='check')
    op.create_check_constraint('check_week_value', 'recurrentschedule','week_day BETWEEN 0 AND 6')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_week_valid', 'recurrentschedule', type_='check')
    op.create_check_constraint('check_week_value', 'recurrentschedule','week_day BETWEEN 1 AND 7')

    # ### end Alembic commands ###
