"""Add check constraint

Revision ID: 775578fec810
Revises: 7299b34e7c22
Create Date: 2025-04-24 22:36:01.216344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775578fec810'
down_revision: Union[str, None] = '7299b34e7c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.REAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
