"""Correccion foreign key de meeting

Revision ID: 86c93608f3dc
Revises: b04c527b43cd
Create Date: 2025-05-14 02:31:01.222038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c93608f3dc'
down_revision: Union[str, None] = 'b04c527b43cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('topic', sa.String(), nullable=False))
    op.create_foreign_key(None, 'meeting', 'topic', ['topic'], ['topic_name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'topic')
    # ### end Alembic commands ###
