"""Create Table RecurrentSchedule

Revision ID: 8eb396d12730
Revises: b34295c8b11e
Create Date: 2025-04-30 20:27:55.421006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb396d12730'
down_revision: Union[str, None] = 'b34295c8b11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrentschedule',
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.CheckConstraint('week_day BETWEEN 1 AND 7 ', name='check_week_valid'),
    sa.ForeignKeyConstraint(['prof_id'], ['professional.prof_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('week_day', 'start', 'prof_id')
    )
    op.create_table('specificschedule',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('isCanceling', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prof_id'], ['professional.prof_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'start', 'prof_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specificschedule')
    op.drop_table('recurrentschedule')
    # ### end Alembic commands ###
