"""Create Table Professional

Revision ID: 93c4df85e1ec
Revises: a89bc6110f3b
Create Date: 2025-04-30 20:26:34.597933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c4df85e1ec'
down_revision: Union[str, None] = 'a89bc6110f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 5', name='check_score_valid'),
    sa.ForeignKeyConstraint(['prof_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prof_id')
    )
    op.create_index(op.f('ix_professional_prof_id'), 'professional', ['prof_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_prof_id'), table_name='professional')
    op.drop_table('professional')
    # ### end Alembic commands ###
