"""Create Table TopicRecurrent

Revision ID: 97d29761ced9
Revises: 2aba5c71ecf4
Create Date: 2025-04-30 20:28:46.883561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d29761ced9'
down_revision: Union[str, None] = '2aba5c71ecf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicrecurrent',
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prof_id', 'topic_name'], ['professionaltopic.prof_id', 'professionaltopic.topic_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_id', 'week_day', 'start'], ['recurrentschedule.prof_id', 'recurrentschedule.week_day', 'recurrentschedule.start'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prof_id', 'topic_name', 'start', 'week_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topicrecurrent')
    # ### end Alembic commands ###
