"""create Table Specific

Revision ID: 99a9937f6aa7
Revises: 74006464cd14
Create Date: 2025-04-21 16:21:07.536174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a9937f6aa7'
down_revision: Union[str, None] = '74006464cd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specificschedule',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('isCanceling', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profesional.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day', 'start', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specificschedule')
    # ### end Alembic commands ###
