"""Update User and reservation

Revision ID: a2523907288a
Revises: 3ed878c5e89c
Create Date: 2025-06-10 19:49:11.843314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2523907288a'
down_revision: Union[str, None] = '3ed878c5e89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('CBU_CVU', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique_CBU', table_name='users', columns=['CBU_CVU'])
    op.drop_constraint(constraint_name='check_reservation_state', table_name='reservation', type_='check')
    op.create_check_constraint(constraint_name='check_reservation_states', table_name='reservation', condition="state IN ('pending', 'pay', 'cancel_student', 'cancel_professional', 'refund', 'finished')")
    
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='unique_CBU', table_name='users', type_='unique')
    op.drop_column('users', 'CBU_CVU')
    op.drop_constraint(constraint_name='check_reservation_states', table_name='reservation', type_='check')
    op.create_check_constraint(constraint_name='check_reservation_state', table_name='reservation', condition="state IN ('pending', 'finished')")
    # ### end Alembic commands ###
