"""Add check score

Revision ID: ada38ba90ded
Revises: d8ee6cdf0f39
Create Date: 2025-04-24 22:53:52.890581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada38ba90ded'
down_revision: Union[str, None] = 'd8ee6cdf0f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesional', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
