"""Create Table TopicSpecific

Revision ID: b09d1daed132
Revises: 97d29761ced9
Create Date: 2025-04-30 20:32:35.436114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09d1daed132'
down_revision: Union[str, None] = '97d29761ced9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topicspecific',
    sa.Column('prof_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['prof_id', 'day', 'start'], ['specificschedule.prof_id', 'specificschedule.day', 'specificschedule.start'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_id', 'topic_name'], ['professionaltopic.prof_id', 'professionaltopic.topic_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prof_id', 'topic_name', 'start', 'day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topicspecific')
    # ### end Alembic commands ###
