"""add cancelation table

Revision ID: b20dbbbc2388
Revises: f6549d45569c
Create Date: 2025-06-23 19:10:26.084394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20dbbbc2388'
down_revision: Union[str, None] = 'f6549d45569c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelation',
    sa.Column('prof_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('cancel_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('day_hour', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('refund', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("state IN ( 'cancel_student', 'cancel_professional')", name='check_cancel_state'),
    sa.ForeignKeyConstraint(['prof_id'], ['professional.prof_id'], name='fk_professional_cancelation', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name='fk_student_ cancelation', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_hour', 'prof_id', 'student_id', name='pk_cancel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancelation')
    # ### end Alembic commands ###
