"""create Table Topic

Revision ID: b43ed2b4c429
Revises: 0fbe3259b285
Create Date: 2025-04-21 17:27:00.962545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43ed2b4c429'
down_revision: Union[str, None] = '0fbe3259b285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('topic_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
