"""Correccion de foreign keys

Revision ID: c885033a4f7c
Revises: 86c93608f3dc
Create Date: 2025-05-14 02:32:53.974211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c885033a4f7c'
down_revision: Union[str, None] = '86c93608f3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('topic_name', sa.String(), nullable=False))
    op.drop_constraint('meeting_topic_fkey', 'meeting', type_='foreignkey')
    op.create_foreign_key(None, 'meeting', 'topic', ['topic_name'], ['topic_name'], ondelete='CASCADE')
    op.drop_column('meeting', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.create_foreign_key('meeting_topic_fkey', 'meeting', 'topic', ['topic'], ['topic_name'], ondelete='CASCADE')
    op.drop_column('meeting', 'topic_name')
    # ### end Alembic commands ###
