"""fix topic recurrent

Revision ID: da5c36734d7b
Revises: 0aae468f8f07
Create Date: 2025-04-21 21:40:15.470232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5c36734d7b'
down_revision: Union[str, None] = '0aae468f8f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'topicrecurrent', 'recurrentschedule', ['user_id', 'start', 'name_day'], ['user_id', 'start', 'name_day'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topicrecurrent', type_='foreignkey')
    # ### end Alembic commands ###
