apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: myapp
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: mydatabase
  DB_USER: myuser
  PAYPAL_API_URL: https://api-m.sandbox.paypal.com # cambiar entorno sandbox / produccion
  CLIENT_ORIGIN_URL: https://miplasip.publicvm.com/